quarkus.container-image.image=dthibau/quarkus-greetings

quarkus.kubernetes.deploy=true
quarkus.kubernetes.namespace=default

quarkus.kubernetes.service-type=node-port
quarkus.package.type=mutable-jar
quarkus.kubernetes.env.vars.quarkus-launch-devmode=true
quarkus.live-reload.password=secret
quarkus.live-reload.url=http://172.23.0.2:31472/