quarkus.http.port=8003
quarkus.http.auth.basic=true

%dev.quarkus.security.users.embedded.enabled=true
%dev.quarkus.security.users.embedded.plain-text=true
%dev.quarkus.security.users.embedded.users.scott=reader
%dev.quarkus.security.users.embedded.users.stuart=writer
%dev.quarkus.security.users.embedded.roles.scott=READER
%dev.quarkus.security.users.embedded.roles.stuart=READER,WRITER

#mp.messaging.incoming.orders-in.connector=smallrye-kafka
mp.messaging.outgoing.order-out.topic=order
#mp.messaging.incoming.orders-out.value.serializer=