quarkus.http.port=8000

# Configuration service de notification
notification.host=localhost
notification.port=8080
notification.protocol=http
notification.url=${notification.protocol}://${notification.host}:${notification.port}
notification.token=secret
quarkus.rest-client.notification-api.url=${notification.url}

quarkus.log.level=INFO
quarkus.log.category."org.formation".level=DEBUG
quarkus.log.category."io.vertx.pgclient.impl".level=DEBUG

quarkus.hibernate-orm.log.sql=true

quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = postgres
quarkus.datasource.password = postgres

quarkus.datasource.reactive.url=postgresql:///livraison

quarkus.hibernate-orm.database.generation=drop-and-create

%prod.quarkus.http.port=9000
