quarkus.http.port=8000

# Configuration service de notification
notification.host=localhost
notification.port=8080
notification.protocol=http
notification.url=${notification.protocol}://${notification.host}:${notification.port}
notification.token=secret
quarkus.rest-client.notification-api.url=${notification.url}

quarkus.log.level=DEBUG
quarkus.log.category."org.formation".level=DEBUG

%prod.quarkus.http.port=9000
