quarkus.http.port=8000

# Configuration service de notification
notification.host=localhost
notification.port=8080
notification.protocol=http
notification.url=${notification.protocol}://${notification.host}:${notification.port}
notification.token=secret
quarkus.rest-client.notification-api.url=${notification.url}

quarkus.log.level=INFO
quarkus.log.category."org.formation".level=DEBUG

quarkus.hibernate-orm.log.sql=true

%reactive.quarkus.datasource.username=postgres
%reactive.quarkus.datasource.password=postgres
%reactive.quarkus.datasource.reactive.url=postgresql:///livraison
%reactive.quarkus.datasource.reactive.max-size=20

%prod.quarkus.http.port=9000


quarkus.container-image.image=dthibau/quarkus-delivery

quarkus.kubernetes.deploy=true
quarkus.kubernetes.namespace=default

#quarkus.kubernetes.service-type=node-port
#quarkus.package.type=mutable-jar
#quarkus.kubernetes.env.vars.quarkus-launch-devmode=true
#quarkus.live-reload.password=secret
#quarkus.live-reload.url=http://172.23.0.2:31472/

quarkus.kubernetes.labels.app-type=delivery
quarkus.kubernetes.annotations.app-type=delivery
quarkus.kubernetes.env.secrets=postgres-secret
quarkus.kubernetes.env.configmaps=postgres-config

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
quarkus.hibernate-orm.database.generation=update

# dev
%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.username=sa
%dev.quarkus.datasource.password=password
%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
# test
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=password
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb
%test.quarkus.hibernate-orm.database.generation=drop-and-create


 